name: ecommerce
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

#---------------------Packages---------------------#
dependencies:
  flutter:
    sdk: flutter

  # ---------Packages utilities--------- #

  http: ^1.3.0
  intl: ^0.20.2
  get: ^4.7.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  get_storage:
  flutter_native_splash: ^2.4.6
  # ---------Packages icons--------- #

  cupertino_icons: ^1.0.8
  smooth_page_indicator:
    ^1.2.1

    # ---------Packages Product specific--------- #

    # ---------Packages states management--------- #

  # ---------Packages ENd--------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design:
    true

    # ---------Local assets--------- #

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/logos/

    # ---------Local Fonts--------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

    # ---------Local Icons--------- #
